### ISSUE TITLE
Cloning an instance of rp3d::DynamicsWorld

### ISSUE THREAD

**Issue by Omroth** [DanielChappuis/reactphysics3d#114]
First, can I clone a Dynamics World by just assinging a new one:

rp3d::DynamicsWorld new_one = other_d_world;

Would you expect this to work fine?

Second, if I have pointers to objects such as rp3d::RigidBody or ProxyShape for the first dynamics_world, what is the best way to find the corresponding rigidBody or ProxyShape in the cloned world?

Thanks.

**Comment by DanielChappuis** [comment]
Sorry but you cannot clone a DynamicsWorld like that. The only way I see is to recreate it. Can I ask you why you want to do that ?

**Comment by Omroth** [comment]
That's annoying, I have to say - I was assuming there'd be a simple clone ability given that it's a very lightweight library.

I want to run multiple simulations in different threads with small changes, which needs this really.

I can recreate it instead, but getting the current state identical - velocities etc - is going to be hard/impossible.

**Comment by DanielChappuis** [comment]
I am not sure that any other physics engine library (PhysX, Bullet, ...) allows you to clone a complete physics world.

**Comment by Omroth** [comment]
Understood - but it seems odd to me, can you not just clone every object in the world?  What's the complication?

**Comment by DanielChappuis** [comment]
Of course it can be done but I have never had the idea to implement this because it's the first time I hear someone with this request. Implement this would take some time because it is not sufficient to clone the public objects (bodies, joints, ...) but also all the internal cached data of the physics engine and this would take quite some time. I don't currently plan to implement this.
