### ISSUE TITLE
Does each triangle mesh subpart have its own AABB during broadphase collision detection?

### ISSUE THREAD

**Issue by Silberklinge** [DanielChappuis/reactphysics3d#130]
If there is a concave collision shape backed by a `rp3d::TriangleMesh` composed of multiple subparts, does each subpart get its own AABB during broadphase collision detection, or is there only one AABB for the entire `rp3d::TriangleMesh` that encompasses all subparts? I need to know whether I can create a large terrain using one `rp3d::TriangleMesh` with (possibly hundreds of) subparts, for easier management, without slowing my simulation to a crawl.

**Comment by DanielChappuis** [comment]
You can use the [rp3d::ConcaveMeshShape](https://reactphysics3d.com/usermanual.html#x1-4300010.5). In order to create a ConcaveMeshShape, you need to provide a rp3d::TriangleMesh that can contain several parts (sub-meshes). Internally, each ConcaveMeshShape has a Dynamic AABB tree with all the triangles for the broad-phase collision detection.

Note that if you need to represent a terrain, you can also use the [rp3d::HeightFieldShape](https://reactphysics3d.com/usermanual.html#x1-4400010.6).

I hope this helps.

**Comment by DanielChappuis** [comment]
I am closing this issue. Do not hesitate to reopen it again if needed.
