### ISSUE TITLE
Automatically Destroying Bodies, etc in Collision/Dynamics World's Destructors

### ISSUE THREAD

**Issue by jagoly** [DanielChappuis/reactphysics3d#14]
As title, I'm curious what the reason is for requiring the user to manually destroy all Bodies and Joints. The objects are created by using methods of a World object, and immediately added to it - they can never live longer than the World object. Thus, it makes no sense to require the user to manually delete them. In many cases, it requires a great deal of effort to keep track of them. To make things worse, the sets of pointers that the World objects already store are protected, making it impossible to destroy them in the destructor of the object containing the World.

This also applies to Bodies and Shapes, in that a ProxyShape can never outlive the Body, so requiring that it be destroyed manually is pointless.

I propose that CollisionWorld and DynamicsWorld both be modified to automatically destroy all of their Bodies and Joints, and Bodies their Shapes. This would be a far more reasonable design that would allow immense amount more flexibility for end users.

**Comment by jagoly** [comment]
Actually, I just noticed that RigidBody actually already does this, I misread the documentation. Sorry! However, it certainly does still apply to Collision / Dynamics World, Bodies and Joints.

**Comment by DanielChappuis** [comment]
Yes, you are right. A body or a joint cannot outlive the World in which they have been added. However, they life can be shorter. A user should be able to call the destroyBody() or destroyJoint() methods if he wants to remove a body or a joint from the world before the end of the application for instance (for optimization because the object is not visible anymore, etc). Therefore,  we need to keep those two methods to manually remove a body or a joint from the world.

I agree with you, the world destructor should be smarter. I propose to change the CollisionWorld and DynamicsWorld destructors so that they call the destroyBody() or destroyJoint() methods on every bodies or joints that have not been removed from the World yet.

It means that the user will still be able to manually remove a body (or joint) but if he doesn't, the World destructor will remove it automatically at the end.

**Comment by jagoly** [comment]
Yes, that is exactly what I meant. Of course we still need to keep the destroy methods, for that reason. Splendid! :)

**Comment by DanielChappuis** [comment]
OK perfect. I will take care of this for the next release. Thanks a lot for reporting this.

**Comment by DanielChappuis** [comment]
I have implemented this in the commit 345afc1a1dc61e42b0a93dcf1e3696b1a84d6ec0 in the develop branch.

This will be available in the next release of the library.
