### ISSUE TITLE
ReactPhysics3D simulation quite unstable

### ISSUE THREAD

**Issue by Omroth** [DanielChappuis/reactphysics3d#141]
It doesnt take many in game ticks before my simulation, which is 15 kinetic bodies attached by simple hinge joints and a floor polygon, to "blow up" and go crazy.  Are there any settings or easy tweaks to improve the stability of the simulation?

Thanks.

**Comment by DanielChappuis** [comment]
Thanks for your feedback.

Can you try to make a video so that I can see what it looks like ?

You can also try to increase the number of iteration of the velocity solver using the DynamicsWorld:: setNbIterationsVelocitySolver() method. This value is 10 by default.

You can also try to increase the number of iteration of the position solver using the DynamicsWorld:: setNbIterationsPositionSolver() method. This value is 5 by default.

Note that increasing those values should make the simulation more precise but also slower.

Can you also try simplify your example by using only one joint for instance and see what happens ?

**Comment by Omroth** [comment]
Thanks Daniel.

I tried increasing the iterations for the velocity solver and the position solver (to 30 and 20 respectively) and it didn't help.

I have a little robot guy flexing on the floor:

![Screenshot from 2020-04-26 08-17-24](https://user-images.githubusercontent.com/48519294/80300638-67878400-8796-11ea-8d74-4d82de7add2c.png)

I iterate this a while (32 ms per physics tick) and this happens pretty quickly - it starts flying into the air a bit:

![Screenshot from 2020-04-26 08-18-50](https://user-images.githubusercontent.com/48519294/80300668-9c93d680-8796-11ea-9c02-0c10e162a4f6.png)

Starts going crazier:

![Screenshot from 2020-04-26 08-19-25](https://user-images.githubusercontent.com/48519294/80300672-ac131f80-8796-11ea-87e1-26be4ad60dda.png)

And then just explodes:

![Screenshot from 2020-04-26 08-19-48](https://user-images.githubusercontent.com/48519294/80300680-b9300e80-8796-11ea-8aa8-2110b685880d.png)

Any ideas?
Thanks.

**Comment by DanielChappuis** [comment]
Are you able to simplify your simulation with only two bodies attached with a hinge joint and see how it behaves ? Do you have some code that I can try to reproduce your bodies and joints setup ?

**Comment by Omroth** [comment]
Two boddies attached with a hinge joint doesn't do much and doesn't immediately break.

This setup works ok when it's just allowed to fall under gravity to the ground.  But when I start applying forces to the bodies it quite quickly explodes.  The behavior looks like there's some divide by small number getting introduced maybe.

I'd love to be able to share the code, but the setup is the result of quite a long chain of different tools to get to the simulation running...

**Comment by DanielChappuis** [comment]
> Two boddies attached with a hinge joint doesn't do much and doesn't immediately break.

So you mean that if you do not apply any force it doesn't break at all or it also break after some time ?

In your first message, you said you have 15 kinetic bodies. Are you saying that you have 15 bodies with type KINEMATIC instead of DYNAMIC ? Note that applying forces to KINEMATIC bodies is not possible.

> This setup works ok when it's just allowed to fall under gravity to the ground. But when I start applying forces to the bodies it quite quickly explodes. The behavior looks like there's some divide by small number getting introduced maybe.

Can I ask you how do you apply forces exactly ? Which method are your using ? What kind of force values are your passing ? Are you calling the method each frame ?

> I'd love to be able to share the code, but the setup is the result of quite a long chain of different tools to get to the simulation running...

Sure, I understand.

**Comment by Omroth** [comment]
Sorry, no I meant Dynamic.  How I create my objects is attached at the bottom of this post.

I apply forces like this:

`Point3F force_apply_position_global = joint->child.chunk->getChunkMidPoint();
    joint->child.chunk->mLocalToWorldTransform.mulP(force_apply_position_global);

    Point3F my_pos_global = joint->mGlobalPos;
    Point3F to_midpoint_normal = force_apply_position_global - my_pos_global;
    to_midpoint_normal.normalize();

    Point3F my_axisvec_global = axisVec;
    joint->parent.chunk->mLocalToWorldTransform.mulV(my_axisvec_global);
    
    Point3F direction_of_force = mCross(to_midpoint_normal, my_axisvec_global);

    Point3F force_vector = direction_of_force * force;

    joint->child.chunk->dbody->applyForce(to_react_vector(force_vector), to_react_vector(force_apply_position_global));`

The maximum force I apply to any body is per second is 500, so approx 500 / 32 per tick.

And yes, I am calling this each frame.

The mass of each body is between about 0.2kg and 2kg.

Your help is really appreciated on this.  I'm wondering whether increasing the damping might be effective?

`Point3F chunk_center_global = getChunkMidPoint();
    mLocalToWorldTransform.mulP(chunk_center_global);

    MatrixF just_rot = mLocalToWorldTransform;
    just_rot.setPosition(Point3F(0,0,0));
    
    QuatF quat = QuatF(just_rot);

    quat.inverse();

    rp3d::Transform transform(to_react_vector(chunk_center_global), to_react_quat(quat));

    dbody = dworld->createRigidBody(transform);

    dbody->setAngularDamping(rp3d::decimal(0.2));
    dbody->setLinearDamping(rp3d::decimal(0.2));

    //

    // Half extents of the box in the x, y and z directions
    const rp3d::Vector3 halfExtents(world_size.x * 0.5, world_size.y * 0.5, world_size.z * 0.5);

    // Create the box shape
    dcolshape = new rp3d::BoxShape(halfExtents);

    dproxyshape = dbody->addCollisionShape(dcolshape, rp3d::Transform::identity(), rp3d::decimal(mass * 0.1)); // React3D works better with smaller masses maybe


    ////

    if (parent)
    {
        // Anchor point in world-space 
        const rp3d::Vector3 anchorPoint = to_react_vector(parentJoint->mGlobalPos); 

        JointAxis* joint_axis = parentJoint->axes[0];
        
        // Hinge rotation axis in world-space 
        const rp3d::Vector3 daxis = to_react_vector(parentJoint->get_global_axis_vec_for(joint_axis));
        
        // Create the joint info object 
		/*rp3d::BallAndSocketJointInfo jointInfo(parent->dbody, dbody, anchorPoint);
		jointInfo.isCollisionEnabled = false; 
		djoint = dynamic_cast<rp3d::BallAndSocketJoint*>(dworld->createJoint(jointInfo));
		*/

		
		rp3d::HingeJointInfo jointInfo(parent->dbody, dbody, anchorPoint, daxis);

        // Enable the limits of the joint 
        jointInfo.isLimitEnabled = true; 
        
        // Minimum limit angle 
        jointInfo.minAngleLimit = mDegToRad(joint_axis->minVal); 
        
        // Maximum limit angle 
        jointInfo.maxAngleLimit = mDegToRad(joint_axis->maxVal);  

        // Disable the collision between the bodies 
        jointInfo.isCollisionEnabled = false; 

        djoint = dynamic_cast<rp3d::HingeJoint*>(dworld->createJoint(jointInfo));
		
    }
    `

**Comment by Omroth** [comment]
Sorry, I didn't answer this question:

> So you mean that if you do not apply any force it doesn't break at all or it also break after some time ?

No, it doesn't break at all if I do not apply forces.

**Comment by DanielChappuis** [comment]
Are you applying a force to a single body of multiple bodies ? Do you apply a force to only one of the two bodies of the hinge joint or to both bodies ?

Is it possible that you are applying a force too strong and the constraint of the joint cannot be fulfilled ?

Can you try to reduce the force and see if it still breaks ?

Does it also break if you disable the joints limits (jointInfo.isLimitEnabled = false) ?

**Comment by Omroth** [comment]
I apply a force to only one body *at a time*, but I am applying forces to all of the bodies over time.

If I disable the joints limit it does "fix" the problem, but I do need limits... what can I do?  Do you have any concepts for how to change the limits to not cause this problem?  I'm very happy to dig into the code and try to implement things.

(Increasing the damping from 0.2 to 0.4 did not help at all.)

Reducing the force helps but, again, stops my guy being able to move at all usefully, so isn't really a solution.

**Comment by DanielChappuis** [comment]
> If I disable the joints limit it does "fix" the problem, but I do need limits... what can I do? Do you have any concepts for how to change the limits to not cause this problem? I'm very happy to dig into the code and try to implement things.

> Reducing the force helps but, again, stops my guy being able to move at all usefully, so isn't really a solution.

Yes sure those are not solutions, I am just trying to understand when the issue occurs

What could help is if you can simplify the setup. Are you able to make the issue happens only with two bodies only attached with a single hinge joint where you apply the force. If you can can do this single setup and reproduce the issue, I will also be able to create this simple setup on my side and try to understand what is going on.

**Comment by Omroth** [comment]
I'll try with just two bodies, thanks Daniel.

**Comment by Omroth** [comment]
I'm able to replicate it with three bodies.  Is there a way I can save the state of the simulation to give to you, or output a log of all calls so you can replicate them?

**Comment by DanielChappuis** [comment]
Unfortunately, there is currently no way to automatically share the current state of the physis world.

I suggest that you post here the code that you use to create your bodies (collision shapes, transforms, ...) and joints and the code that you use each frame to apply a force and I can try to reproduce the issue on my side.

**Comment by Omroth** [comment]
Ok, here is a log of I think all calls.  I'm hoping you can do something with this!  I stop the simulation as soon as I see it blow up.

[rphys_log.txt](https://github.com/DanielChappuis/reactphysics3d/files/4567266/rphys_log.txt)

**Comment by Omroth** [comment]
Oh I made a mistake in the logging of the forces; fixed it here.
[console.log](https://github.com/DanielChappuis/reactphysics3d/files/4567281/console.log)

**Comment by DanielChappuis** [comment]
Hello,

I have fixed something with the limits of the HingeJoint in this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/c1f40ac45618fbeceddbbe0ab909457e076bd7f1) in the master branch. Can you please pull this change and see if it improves your simulation ?

I am not sure this fix is related to your issue but I would like to know if it is the case or not.

I have reproduced your setup on my side (boxes and joints) but I cannot really apply the force exactly as you do because your force and the position where it is applied change each frame and therefore I cannot reproduce it exactly programmatically. For the moment, I have your setup and when I apply no force the three boxes are just falling on the floor (not breaking) and if I apply a force to one of the bodies (it moves or fly but still not breaking). I am not sure I really understant where you apply your forces. Are you applying them to a fixed point of the moving body that moves (so the point also moves) ? 

Aren't your bodies falling on the floor with gravity ? I mean, in your log the y value of the point where the force is applied to your second body seems to stay in the range [6; 10]. It doesn't seem that your bodies are falling down ? Is is because of the force you apply ?

Are you able to let me know exactly how can I compute the same forces you apply to your bodies (force direction, force length and force position) ? 

Could you also post a small video or GIF of your setup with and without force (not breaking and breaking) so that I can see what it looks like ?

Thanks for your help.

**Comment by Omroth** [comment]
That commit seems to have fixed the issue - thank you so much Daniel.  I very much appreciate you going to the effort of trying to replicate my setup.

I'll be back if I run into anything else.

**Comment by DanielChappuis** [comment]
That's great news !!

That's me who would like to thank your for taking the time to report and explain the issue so that I can fix it !

**Comment by Omroth** [comment]
No problem at all!

Don't suppose I could persuade you to put limits on the ball joint could I? :)

**Comment by DanielChappuis** [comment]
For the moment, my focus is to release the version 0.8.0 of the library but then, I can try to implement limits for the Ball joint. Maybe you can create a new issue with this request to keep track of it.

**Comment by Omroth** [comment]
Thank you Daniel.
