### ISSUE TITLE
Compiling on x64 Windows with testbed give cmake error

### ISSUE THREAD

**Issue by kingc8** [DanielChappuis/reactphysics3d#152]
Issue regarding latest 0.8.0:

![image](https://user-images.githubusercontent.com/3446076/83385458-90c8af00-a3e9-11ea-9b77-362101df9e5a.png)

It works fine if testbed is not selected for build.

**Comment by DanielChappuis** [comment]
Thanks for reporting this.

I have just pushed some modifications in this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/6008d25bfc599da18c4b02a6e87397181d36fba6) in the master branch. Could you try again ?

Note that in the version v0.8.0 of the library, the dependencies of the testbed application are cloned using "git submodules" command. This is done automatically in CMake if you enable the compilation of the testbed application. Therefore, you need to have "git" installed on your system and CMake needs to be able to find it.

**Comment by kingc8** [comment]
I installed GIT and made sure it installed with the PATH populated so that 3rd party systems like Visual Studio could find it.
![image](https://user-images.githubusercontent.com/3446076/83487737-d948a100-a4ab-11ea-8c53-a77bd366f16c.png)

**Comment by kingc8** [comment]
I normally just download the package as a zip and unzip it, create a build directory in main folder and use that as a build target.

On windows I don't usually use the GIT command line system.

**Comment by DanielChappuis** [comment]
The previous error is probably due to the fact that your are inside the zip package instead of a real git repository. You need to clone the ReactPhysics3D repository on your system using git. CMake displays this error because it didn't find a ".git" folder.

Yes this is necessary to compile the testbed application because I am using git submodules to get the dependencies. This is cleaner than previous version were the code of the dependencies (nanogui library) was copy/pasted into the ReactPhysics3D repository. This is now cleaner but Git is required (only to compile the testbed not the library itself).

**Comment by kingc8** [comment]
That's understood. -As found already and you have explained, the library compiles without this requirement anyway.

Thanks Daniel. I think this point can be closed then.

**Comment by DanielChappuis** [comment]
Ok perfect. Thanks.
