### ISSUE TITLE
Matrix3x3 to Quaternion Conversion

### ISSUE THREAD

**Issue by GreenLightning** [DanielChappuis/reactphysics3d#157]
Hi,

thanks for making a great library!

I noticed some strange rotation in the output from the debug renderer when setting the transform of a body using a Matrix3x3. The problem went away when converting to a quaternion using GLM, so I believe the problem is in the Matrix3x3 to Quaternion conversion. Here is some example code:

```
Matrix3x3 original(0.001743,-0.968608,0.248589,-0.614229,-0.197205,-0.764090,0.789126,-0.151359,-0.595290);
Matrix3x3 converted = Quaternion(original).getMatrix();
std::cout << original.to_string() << std::endl;
std::cout << converted.to_string() << std::endl;
```

Output:

```
Matrix3x3(0.001743,-0.968608,0.248589,-0.614229,-0.197205,-0.764090,0.789126,-0.151359,-0.595290)
Matrix3x3(0.124709,-0.992193,-0.000000,-0.784941,-0.098659,-0.611665,0.606890,0.076281,-0.791117)
```

**Comment by DanielChappuis** [comment]
Hello. Thanks a lot for taking the time to report this issue.

I have made a fix with this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/3b2f973ffdffbcbfaa998bc59bb478a245d631a7) in the master branch.

Could you pull this change and let me know if the issue is also fixed on your side ?

**Comment by GreenLightning** [comment]
Yes, it is fixed now. Thanks!
