### ISSUE TITLE
Basic box with simple GUI(OpenGL, or Glut)

### ISSUE THREAD

**Issue by GitJonibek** [DanielChappuis/reactphysics3d#161]
I appreciate your work and I also I wanted to ask to push some kind of very simple demo using some GUI libs. 

Can you show or put the demo which uses ReactPhysics3D and draw for ex: Box in a window? I would love to see that because it is very difficult to even start with this lib for beginners. 

Thanks beforehand.

**Comment by DanielChappuis** [comment]
Hello.

The repository contains a "[testbed](https://github.com/DanielChappuis/reactphysics3d/tree/master/testbed)" application with multiple demos (rendered using OpenGL) as you can see [here](https://reactphysics3d.com/usermanual.html#x1-7300014). Take a look at the documention (see below) in order to compile this application.

I also suggest that you take a look at the hello world sample in order to see how to compile and use the ReactPhysics3D library in your project. This can be found [here](https://github.com/DanielChappuis/reactphysics3d/tree/master/helloworld).

Note that you can find the documentation of the library [here](https://reactphysics3d.com/documentation.html).

I hope this helps.

**Comment by DanielChappuis** [comment]
Can I close this issue ?

**Comment by GitJonibek** [comment]
> Can I close this issue ?

Yes, thank you btw for your response
