### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by ColinGilbert** [DanielChappuis/reactphysics3d#17]
The examples take up all available CPU resources. I looked at the setup code and the physics world's timestep seems to be set correctly. Furthermore, when I (hackishly) set the GLFW main loop to only update the physics world once every 1/N (N = 60 to 120) seconds, CPU usage went back down to something reasonable.

**Comment by jagoly** [comment]
That sounds like you should turn on vsync. I don't have the old examples here to test (only the testbed, which is currently broken).

**Comment by DanielChappuis** [comment]
Thanks for reporting this. I am currently working on the testbed application (that will replace the examples) in the next release. I will activate the vsync on it. The testbed will be ready soon and the "testbed" branch will be merged into the "develop" branch.

**Comment by DanielChappuis** [comment]
I have finished the first version of the testbed application in order to replace the "examples". In the testbed application, vsync is enabled by default and can be switched off. I have merged everything in the "develop" branch. Therefore, this will be available in the next version of the library. 

If you want to enable the vsync in the "examples", you need to use the glfwSwapInterval() method as described here: http://www.glfw.org/docs/latest/group__context.html#ga6d4e0cdf151b5e579bd67f13202994ed
