### ISSUE TITLE
Place dynamic body on top of static body, dynamic body moves unpredictably for several frames?

### ISSUE THREAD

**Issue by caturria** [DanielChappuis/reactphysics3d#172]
Hi,
I am new to working with physics APIs, so please forgive me if I'm missing something obvious.
In the following example, I place out a static body to represent the ground, and then a dynamic body on top of the ground to represent the character.
I am as certain as I can be that I have placed the body in such a way as to have it perfectly flush with the surface of the ground, however it seems to behave as if it was dropped to the ground from a height rather than having simply been spawned there, as it is in motion from the get go and takes quite a few frames to stabilize.
Please forgive the quick and dirty console based example, as a blind person I cannot produce a graphical demo.
#define IS_RP3D_DOUBLE_PRECISION_ENABLED
#include <reactphysics3d/reactphysics3d.h>
#include <iostream>//std::cout
using namespace reactphysics3d;

int main(int argc, char* argv[])
{
    PhysicsCommon physics;
    PhysicsWorld* world = physics.createPhysicsWorld();
//I prefer to have the up direction represented by the Z axis.
    world->setGravity(Vector3(0.0, 0.0, -10.0));
//Create a floor with the surface at exactly 0.
    RigidBody* floor = world->createRigidBody(
                                              Transform(Vector3(25.0, 25.0, -0.1), Quaternion::identity()));
    BoxShape* shape = physics.createBoxShape(Vector3(25.0, 25.0, 0.1));//Floor will extend from -0.2 to 0.0 along the Z axis.
floor->addCollider(shape, Transform::identity());
    floor->setType(BodyType::STATIC);
//Just make the character a box with simple numbers for the time being for the sake of demonstration.
    RigidBody* person = world->createRigidBody(Transform(Vector3(25.0, 25.0, 1.0-DBL_EPSILON), Quaternion::identity()));//Character should be perfectly flush with surface of ground.
    shape = physics.createBoxShape(Vector3(1.0, 1.0, 1.0));
    person->addCollider(shape, Transform::identity())->getMaterial().setMassDensity(10.1875);//Mass=81.5KG
    person->updateMassPropertiesFromColliders();
    Vector3 pos = person->getTransform().getPosition();
    int frames = 0;
//Report how many frames it takes for the character to stabilize.
    while(true)
{
    world->update(1.0/60);
    Vector3 newPos = person->getTransform().getPosition();
if(pos == newPos)
    break;
    pos = newPos;
    frames++;
    std::cout << pos.to_string() << std::endl;
}
    std::cout << "Finally came to rest after " << frames << " frames." << std::endl;
    
}
It produces the following output:

Vector3(24.999999,24.999999,1.000000)
Vector3(25.000627,24.999940,0.998711)
Vector3(25.000635,24.999936,0.998717)
Vector3(25.000234,24.999958,0.997304)
Vector3(25.000233,24.999960,0.997305)
Vector3(25.000233,24.999959,0.997304)
Vector3(25.000233,24.999959,0.997304)
Vector3(25.000233,24.999959,0.997304)
Vector3(25.000233,24.999959,0.997304)
Vector3(25.000233,24.999959,0.997304)
Vector3(25.000233,24.999959,0.997304)
Vector3(25.000233,24.999959,0.997304)
Vector3(25.000233,24.999959,0.997304)
Finally came to rest after 13 frames.

Please advise,

Jordan.

**Comment by DanielChappuis** [comment]
Hello,

Thanks for your feedback. I am not sure I really understand what you are expecting in this case.

In the output that you have posted, I see that the final position (Vector3(25.000233,24.999959,0.997304)) is already the one in the 6th frame not the 13th frame and does it really matters ? What do you expect exactly ? A game physics library is supposed to approximate the simulation in order to have something that is visually plausible but not physically perfect.
I think it's correct behavior that it stabilizes after some frames and 6 frames is really not a lot for a real-time 60 FPS simulation.

Also note that you use a floating point equality test to know when the position has stabilized. Note this condition might even never been evaluated to true even after the position has stabilized if the newPos is very close but not exactly the same as the initial position.

**Comment by DanielChappuis** [comment]
I am closing this issue. Do not hesitate to reopen it if something is not clear.
