### ISSUE TITLE
macOS error building testbed 

### ISSUE THREAD

**Issue by rcallagh** [DanielChappuis/reactphysics3d#176]
I'm trying to install ReactPhysics3D on macOS 10.15.6 using the cmake defaults, other than toggling `RP3D_COMPILE_TESTBED` to true. After using ccmake to configure and generate build files I get an error when calling make at the stage: 
```
Scanning dependencies of target testbed
[ 79%] Building CXX object testbed/CMakeFiles/testbed.dir/src/Main.cpp.o
```

There are a lot of warnings thrown up but the actual error happens here 
```
In file included from /Users/rcallagh/reactphysics3d/testbed/src/Main.cpp:27:
In file included from /Users/rcallagh/reactphysics3d/testbed/src/TestbedApplication.h:30:
In file included from /Users/rcallagh/reactphysics3d/testbed/opengl-framework/src/openglframework.h:39:
/Users/rcallagh/reactphysics3d/testbed/opengl-framework/src/VertexArrayObject.h:78:5: error:
      use of undeclared identifier 'glBindVertexArray'
    glBindVertexArray(mVertexArrayID);
    ^
/Users/rcallagh/reactphysics3d/testbed/opengl-framework/src/VertexArrayObject.h:86:5: error:
      use of undeclared identifier 'glBindVertexArray'
    glBindVertexArray(0);
```

I'm not sure if this actual error with reactphysics or some kind of macOS opengl incompatibility issue but if you have any way to address this, I'd appreciate it.

**Comment by DanielChappuis** [comment]
Thanks a lot for taking the time to report this issue.

The nanogui library (a dependency needed to build the testbed application) was trying to use Metal instead of OpenGL when building on MacOS X.

I have pushed a [commit](https://github.com/DanielChappuis/reactphysics3d/commit/264705056e95a6d9e5b935af30a8f387132eccf1) to fix this issue in the master branch.

Could you pull again the master branch, clear your CMake cache and try again to build the library with the testbed application and let me know if you still have some issues ?

**Comment by rcallagh** [comment]
Yep, that fixed it for me, thanks, I look forward to exploring ReactPhysics3d!

**Comment by DanielChappuis** [comment]
Perfect. Thanks for your feedback !
