### ISSUE TITLE
Running update four times with 1/4 of the timestep gives different results

### ISSUE THREAD

**Issue by Omroth** [DanielChappuis/reactphysics3d#198]
I have this code:

```
#define N_DWORLD_STEPS 1

for (int i = 0; i < N_DWORLD_STEPS; i += 1)
{
    dworld->update(advance_in_ms / (N_DWORLD_STEPS * 1000.0));
}
```

The physics world behaves quite differently if I set N_DWORLD_STEPS to 1 or 4 (friction appears to be much higher for example).  Why would this be?

(I am trying it like this because the accuracy using one step doesn't appear to be enough.)

I am running with head.  I set up the dworld with:

```
rp3d::PhysicsWorld::WorldSettings settings; 
settings.defaultVelocitySolverNbIterations = 20; 
settings.isSleepingEnabled = false; 
settings.gravity = rp3d::Vector3(0, 0, -9.81); 
dworld = gGameState->physics_common->createPhysicsWorld(settings);
dworld->setNbIterationsVelocitySolver(30);
dworld->setNbIterationsPositionSolver(20);
```

**Comment by DanielChappuis** [comment]
It's not surprising that the physics simulation behaves differently with different timesteps. The smaller the timestep, the more precise is the numerical integration and therefore the simulation.

> (I am trying it like this because the accuracy using one step doesn't appear to be enough.)

I am not sure to understand this. Can you explain a little bit more?

What is `advance_in_ms` in your code exactly?

**Comment by Omroth** [comment]
Hi Daniel, thanks for the reply.

The difference is not on the level of differences in accuracy - a body accelerated under contact at at least twice the rate.

Advance in ms is 32 in this instance.

Best,
Ian

**Comment by DanielChappuis** [comment]
I am not really sure what can cause this behavior in the friction constraint.

**Comment by Omroth** [comment]
Try this.  My output I get is:

Before -5.000000 -5.000000 1.000000
After -4.987674 -4.987674 1.109570
Before -5.000000 -5.000000 1.000000
After -4.978106 -4.978106 1.196050

Which is a huge difference.

```
DefineEngineFunction( test_dworld_ticking, void, (), , "")
{
	rp3d::PhysicsCommon physics_common;

    for (int i = 0; i < 2; i += 1)
    {
        rp3d::PhysicsWorld::WorldSettings settings; 
        settings.defaultVelocitySolverNbIterations = 20; 
        settings.isSleepingEnabled = false; 
        settings.gravity = rp3d::Vector3(0, 0, -9.81); 
        rp3d::PhysicsWorld* dworld = physics_common.createPhysicsWorld(settings);

        // floor

        rp3d::Transform at_origin = rp3d::Transform(rp3d::Vector3(0,0,0), rp3d::Quaternion(0,0,1,0));

        rp3d::RigidBody* floor_body = dworld->createRigidBody(at_origin);
        floor_body->setType(rp3d::BodyType::STATIC);
        const rp3d::Vector3 floor_half_extents(10,10,1);
        rp3d::BoxShape* floor_col_shape = physics_common.createBoxShape(floor_half_extents);
        rp3d::Collider* floor_collider = floor_body->addCollider(floor_col_shape, at_origin);

        // cube
        
        rp3d::RigidBody* cube_body = dworld->createRigidBody(rp3d::Transform(rp3d::Vector3(0,0,0), rp3d::Quaternion(0,0,1,0)));
        const rp3d::Vector3 cube_half_extents(0.5,0.5,0.5);
        rp3d::BoxShape* cube_col_shape = physics_common.createBoxShape(cube_half_extents);
        rp3d::Collider* cube_collider = cube_body->addCollider(cube_col_shape, rp3d::Transform(rp3d::Vector3(5,5,1), rp3d::Quaternion(0,0,1,0)));

        {
            rp3d::Transform tform = cube_collider->getLocalToWorldTransform();
            Point3F pos = to_torque_vector(tform.getPosition());

            print("Before %f %f %f", pos.x, pos.y, pos.z);
        }

        if (i == 0)
        {
            F32 advance_in_seconds = 32.0 / 1000.0;
            dworld->update(advance_in_seconds);
        }
        else
        {
            F32 advance_in_seconds = 32.0 / (1000.0 * 2.0);
            dworld->update(advance_in_seconds);
            dworld->update(advance_in_seconds);
        }

        {
            rp3d::Transform tform = cube_collider->getLocalToWorldTransform();
            Point3F pos = to_torque_vector(tform.getPosition());

            print("After %f %f %f", pos.x, pos.y, pos.z);
        }
    }
}
```

**Comment by DanielChappuis** [comment]
Thanks a lot for your code. I will use this to investigate the issue.

**Comment by DanielChappuis** [comment]
I have investigated this a little bit.

The difference is due to the position correction algorithm (split impulses) for contacts. Because of precision errors and numerical integration errors, the physics engine needs to correct for position drift after solving the velocity constraints.

If we disable position correction, there is no difference between calling the PhysicsWorld::update() method once and calling it twice with half of the time step. There is no way to easily disable position correction for contacts in the library (because it's really important to have it to avoid penetration of bodies). However, you can disable it by commenting the two lines 58 and 59 in src/systems/DynamicsSystem.cpp:

```
newLinVelocity += isSplitImpulseFactor * mRigidBodyComponents.mSplitLinearVelocities[i];
newAngVelocity += isSplitImpulseFactor * mRigidBodyComponents.mSplitAngularVelocities[i];
```

But why is position correction (split impulses) causing this difference. The idea behind "split impulses" is to compute, in each frame, the position error (which is basically the penetration depth between the two bodies). Then, if the penetration depth between the bodies if 5cm for instance, the idea is to correct the position of both bodies such that there is no more penetration depth. However, in order to avoid visual artifacts, we do not want to correct those 5cm in a single frame. It's better to correct a little bit each frame (for instance 20% of the error each frame). Therefore, each frame we correct the position according to the following formula:

`position correction each frame = -beta * penetrationDepth / timeStep;`

where beta is 0.2 in order to fix 20% of the penetration each frame. With this in mind, after some frames, the penetrationDepth is completely corrected.
However, in your example, where you call the PhysicsWorld::update() method only once or twice, the physics engine does not have the time to completely fix the penetration. If you use beta=1 (meaning that we fix the penetration after a single frame), you will see that there are also no differences between your two examples but this value is not feasible in practice because
this will result in visual artifacts. Therefore, I am not really surprised that there is a difference in your two examples when calling only once or twice the PhysicsWorld::update() method.

Concerning the issue that the friction seems much higher when the time step is different, I do not observe this on my side. As a test, I used the testbed application and made an inclined plane with a cube sliding on it. With a time step of 16ms the cube slided on the plane across the screen during 19 seconds. If I use a time of 32ms, 8ms or 4ms the cube takes the same time to slide across the screen.

Note that when I was investigating this, I found an issue with the computation of the two friction vectors. I have fixed it in this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/c273e7cfe580037c6cb7073b0050e0ce7d6da231). Therefore, you should pull the last version of the master branch.

**Comment by Omroth** [comment]
That's great, thank you Daniel - I'll take a look at the fix as well, I was having trouble with some weird friction issues.

**Comment by DanielChappuis** [comment]
Let me know if we can close this issue or if you still need something.
