### ISSUE TITLE
RIgidbody is not moving.

### ISSUE THREAD

**Issue by TheNachoBIT** [DanielChappuis/reactphysics3d#226]
Hello!

This is my first time using RP3D, and i'm using both the user manual and the "hello world" to learn how it works. But for some reason no matter what i do the Rigidbody doesn't move its position at all...

This is the code:
![image](https://user-images.githubusercontent.com/43283743/142630228-2c830d74-68b5-4760-aa5b-26dbe0eee526.png)

and this is the result:
![image](https://user-images.githubusercontent.com/43283743/142630269-786d0800-07cd-4a39-8db2-28520ca094f4.png)

Am i doing something wrong? Am i missing something?

**Comment by DanielChappuis** [comment]
Hello.

I tried to reproduce your code (I was not able to copy/paste it because you posted a picture instead of a code snippet) but on my side it's working. What happens on your side if you run the [hello world](https://github.com/DanielChappuis/reactphysics3d/blob/master/helloworld/Main.cpp) code without any modifications? Does it work?

**Comment by DanielChappuis** [comment]
Hello. Have you been able to try this again? Can I close this issue?

**Comment by TheNachoBIT** [comment]
Oh yeah i'm so sorry, i fixed the issue now!

I forgot a thing in the installation process and i forgot to tell it was fixed.

It was just my fault, you can close the issue now

**Comment by DanielChappuis** [comment]
Ok great. I am glad that you have found the issue. 
Thanks a lot for your feedback.
