### ISSUE TITLE
My cube position doesnt seem to line up correctly with the static floor cube?

### ISSUE THREAD

**Issue by patrikpatrik** [DanielChappuis/reactphysics3d#267]
Hello, sorry for sounding like an absolute noob but I'm trying to understand why this keeps happening.
I have a simple cube that's falling starting at `position 0.0f, 20.0f, 0.0f`

```
// create a rigid body in world
	rp3d::Vector3 position(0.0f, 20.0f, 0.0f);
	rp3d::Quaternion orientation = rp3d::Quaternion::identity();
	rp3d::Transform transform(position, orientation);
	rp3d::RigidBody* body = world->createRigidBody(transform);

	// Half extents of the box in the x, y and z directions 
	rp3d::Vector3 halfExtents(1.0f, 1.0f, 1.0f); // creates a cube 2 meters by 2 meters by 2 meters
	// Create the box shape 
	rp3d::BoxShape* boxShape = physicsCommon.createBoxShape(halfExtents);
	// Add the collider to the rigid body 
	rp3d::Collider* collider;
	collider = body->addCollider(boxShape, transform);
```

Then I have my floor/ground at `position(0.0f, 0.0f, 0.0f)`

```
// create a floor on ground
	rp3d::Vector3 floorPos(0.0f, 0.0f, 0.0f);
	rp3d::Quaternion floorOrientation = rp3d::Quaternion::identity();
	rp3d::Transform floorTransform(floorPos, floorOrientation);
	rp3d::RigidBody* floorBody = world->createRigidBody(floorTransform);
	// change to static
	floorBody->setType(rp3d::BodyType::STATIC);
	// Half extents of the floor box in the x, y and z directions 
	rp3d::Vector3 floorHalfExtents(10.0f, 1.0f, 10.0f); // creates 20.0 by 2.0 by 20.0
	// Create the floor box shape 
	rp3d::BoxShape* floorBoxShape = physicsCommon.createBoxShape(floorHalfExtents);
	// Add the collider to the rigid body 
	rp3d::Collider* floorCollider;
	floorCollider = floorBody->addCollider(floorBoxShape, floorTransform);
```

However, when I examine my cube's position in my loop
```
// get updated position of cube
		const rp3d::Transform& transform = body->getTransform();
		const rp3d::Vector3& position = transform.getPosition();
		rp3d::Vector3 cubeSize = boxShape->getHalfExtents();
```
It falls as usual but stops at position y of -18.0f. Why isn't it stopping at position 0.0 where I created the floor, or at least reasonably near it? Am I doing something horribly wrong?

**Comment by DanielChappuis** [comment]
Hello,

Thanks for your question. First, can I ask you to ask your question in the [discussions section](https://github.com/DanielChappuis/reactphysics3d/discussions) next time? This section is reserved if you think you have found an issue with the library.

Regarding your question. I think the issue is because when you create your bodies, you are using the same initial Transform twice. For instance, when you create the body for your cube, you do:

`rp3d::RigidBody* body = world->createRigidBody(transform);`

This transform is the position/orientation of your body in **world-space**. Therefore, the position of this transform is the translation **from the origin of your world**.

Then, when you add a collider to your rigid body, you do:

`body->addCollider(boxShape, transform)`

The Transform that you pass to the addCollider() method is the position/orientation of your collider **in local-space of your body**. Therefore, the position of this transform is the translation of your collider **from the origin of your body**. In your case, I think your probably want to have the cube collider at the center of your body and therefore, you don't want any translation for your collider. In this case, you need to use the following code instead:

 `body->addCollider(boxShape, Transform::identity())`
 
 The same applies to your floor rigid body.
 
 I hope it helps.

**Comment by patrikpatrik** [comment]
@DanielChappuis My GOD it works now! Thank you so much. And I apologize for posting in the bug section. Please move this and close it. I can't wait to go down the rabbit hole with this so to speak and go nuts. Cheers~

**Comment by DanielChappuis** [comment]
No problem. I hope you will find this library useful.
