### ISSUE TITLE
cleanup ConcaveMeshShape?

### ISSUE THREAD

**Issue by nickblock** [DanielChappuis/reactphysics3d#27]
when I clean up my shapes is there a way of getting the TriangleMesh that created the ConcaveMeshShape? Do I just keep track of those myself?

Also, if I delete the TriangleMesh I go through each TriangleVertexArray part it used and delete those separately. Does that make sense? 

Do I need to delete the ProxyShape(s) created by rigidbody->addCollisionShape?

**Comment by DanielChappuis** [comment]
Hello,

The rule is the following one for cleaning up allocated objects : If you have allocated memory by yourself (using the new operator), you need to clean this memory by yourself (with the delete operator). Otherwise, the memory has been allocated by the physics engine and will be released by the physics engine.

You can find an example of the creation of a concave mesh shape in the testbed application here :
https://github.com/DanielChappuis/reactphysics3d/blob/master/testbed/common/ConcaveMesh.cpp

In this example you can see that I create some TriangleVertexArray as in the following code :

```
// For each subpart of the mesh
for (unsigned int i=0; i<getNbParts(); i++) {

   // Vertex and Indices array for the triangle mesh
   rp3d::TriangleVertexArray* vertexArray = new rp3d::TriangleVertexArray(.....);

   // Add the triangle vertex array of the subpart to the triangle mesh
   triangleMesh.addSubpart(vertexArray);
}
```

As you can see, I allocate memory by myself with the "new" operator. Therefore, I am responsible to delete this memory. I do it with the following code :

```
// Destroy the triangle vertex arrays
for (unsigned int i=0; i<triangleMesh.getNbSubparts(); i++) {
    delete triangleMesh.getSubpart(i);
}
```

I also create the ConcaveMeshShape with the "new" operator as follows :

```
// Create the collision shape
concaveShape = new rp3d::ConcaveMeshShape(&triangleMesh);
```

Therefore I have to delete this shape at the end like this :

```
delete concaveShape;
```

Note that when you add a collision shape to a body, you get back a pointer to the proxy shape as you can see with this code :

```
// Add a collision shape to the body
proxyShape = body->addCollisionShape(concaveShape, rp3d::Transform::identity(), mass);
```

As you can see, you have not allocated memory for the proxy shape by yourself here (no new operator). This memory has been allocated by the physics engine. Therefore, you do not need to delete this object by yourself. The proxy shape will be deleted by the physics engine when you remove the proxy shape from the body or you destroy the body.

I hope this helps.
