### ISSUE TITLE
How to support  "Rollback" ?

### ISSUE THREAD

**Issue by zack-not-know-why-it-work** [DanielChappuis/reactphysics3d#287]
Hi Daniel, 

In the game simulate area, I want to make the physics world state rollback to 1 second ago(maybe 20 frames).  

My solution is to save a queue of WorldState, which contains a list of all PhysicObjectState.  The PhysicObjectState contains Transform \ LinearVelocity \ AngularVelocity.   When do rollback, I set the Transform \ LinearVelocity \ AngularVelocity back to corresponding physic object.

Is these enough? do I need save more info?

**Comment by DanielChappuis** [comment]
Hello,

You might want to store the external force/torque also. I am never tested rolling back the simulation this way. You need to try to you might also experience some weird behaviors because the engine stores internally some data about the previous simulation state which will be broken if you rollback the simulation.

Note: Can I ask you to use the '[Discussions](https://github.com/DanielChappuis/reactphysics3d/discussions)' section next time for your questions instead of opening a new issue?

**Comment by zack-not-know-why-it-work** [comment]
Thanks. I will test it. 

I will use Discussions in future and you can close my issues. Sorry for any inconvenient.

**Comment by DanielChappuis** [comment]
I am closing this issue. Feel free to open a new discussion if necessary.
