### ISSUE TITLE
Custom orientation

### ISSUE THREAD

**Issue by v71** [DanielChappuis/reactphysics3d#294]
Good day, sorry if this is a beginner question I want to use reactphysics3d in my project , and I need to detect collision between 'walls' and convex object, I was wondering if there is some function which accepts an orientation matrix computed somewhere else, since i am not using quaternion.

**Comment by kewldan** [comment]
Hello, 
You should check [this method](https://www.reactphysics3d.com/documentation/api/html/structreactphysics3d_1_1_quaternion.html#a743703efab2ef3c99de9278508c71ac8) to create Quaternion from custom angles 
For example, my Object class has rigidbody member, and it contains position and rotation.

See also:
[Method for get rotation angles from Quaternion](https://www.reactphysics3d.com/documentation/api/html/structreactphysics3d_1_1_quaternion.html#a9e3cdf2646c791363cf918cc1148f965)
[Method to get OpenGL matrix for transformations](https://www.reactphysics3d.com/documentation/api/html/classreactphysics3d_1_1_transform.html#ac3386f91252cc6b0e56ebc21a0e8808b)

**Comment by DanielChappuis** [comment]
Hello. There is also a [constructor ](https://reactphysics3d.com/documentation/api/html/structreactphysics3d_1_1_quaternion.html#a6bdd0d9e131b6f3b8faed8ab25b534c0)of the Quaternion class that takes a rotation matrix.

`Quaternion::Quaternion(const Matrix3x3& matrix)`

Note: Can I ask you next time to ask your question in the [Discussions ](https://github.com/DanielChappuis/reactphysics3d/discussions)section instead of creating a new issue?

**Comment by DanielChappuis** [comment]
I am closing this issue. Feel free to open a new discussion if needed.
