### ISSUE TITLE
Linking with Cmake produces undefined references

### ISSUE THREAD

**Issue by Flibio** [DanielChappuis/reactphysics3d#59]
Hello, I am trying to add react physics to my project; however, I cannot get it to properly function. I am using Cmake to build my project, [here is my `CMakeLists.txt`](https://hastebin.com/xuhixiqofo.lisp). I am on Windows 10 using the MinGW compiler with the CLion IDE. All I have done is include the `reactphysics3d.h` file in `main.cpp`.

As soon as I include the react physics headers, I cannot compile my program because of undefined references.

[The build log containing the error messages](https://hastebin.com/oqojosewun.cpp)

What can I do to resolve this issue?

Thank you.

**Comment by DanielChappuis** [comment]
Hello,

It seems that the linker is not able to find the static library libreactphysics3d.a. Do you have a repository with your code so that I can try to compile ?

Have you tried to add the reference to the static library by hand in your IDE (without the help of the target_link_libraries(Artemis "C:/reactphysics/lib/libreactphysics3d.a") line from your Makefile) ?

**Comment by DanielChappuis** [comment]
Hello,

Have you been able to solve your issue yet ?
Can I close it ?

**Comment by Flibio** [comment]
I solved the issue in a different manner, by making Cmake simply build reactphysics instead of using the precompiled version.

**Comment by DanielChappuis** [comment]
Ok perfect thanks.
