### ISSUE TITLE
Creating Polyhedron Mesh

### ISSUE THREAD

**Issue by auyar1** [DanielChappuis/reactphysics3d#88]
I am trying to create a square pyramid as a polyhedron mesh - 4 outer triangular faces and two base triangular faces.

I am able to successfully create the polygon vertex array, but I am having problems with the polyhedron creation stage.

I am following the progression of shape creation as outlined in the user manual.

I would appreciate help with this!
Thanks

**Comment by auyar1** [comment]
This is my code - I tried using a triangular pyramid (triangle base with triangle faces) to create a triangular mesh and was able to do so. I was then able to create a concave shape.

However, I want to create a convex shape using a polyhedron mesh for a triangle pyramid with a square base.
Any advice would be appreciated!
```
 //array of 5 points, 3 coordinates
        float vertices[15];
        for(int k=0; k<5; k++){
                std::string vert = "v" + std::to_string(k);
                vertices[3*k] = j3["data"]["vertices"][vert]["x"];
                vertices[3*k+1] = j3["data"]["vertices"][vert]["y"];
                vertices[3*k+2] = j3["data"]["vertices"][vert]["z"];
                std::cout << std::setprecision(8);
                std::cout << "added " << vertices[3*k] << "to index" << 3*k << std::endl;
                std::cout << "added " << vertices[3*k+1] << "to index" << 3*k+1 << std::endl;
                std::cout << "added " << vertices[3*k+2] << "to index" << 3*k+2 << std::endl;
        }


        //6 triangle faces
        int indices[18];

        //each face is defined through vertices (ccw)
        //face1
        indices[0] = 0; indices[1] = 2; indices[2] = 1;

        //face2
        indices[3] = 0; indices[4] = 2; indices[5] = 3;

        //face3
        indices[6] = 0; indices[7] = 4; indices[8] = 3;

        //face4
        indices[9] = 0; indices[10] = 1; indices[11] = 4;

        //face5
        indices[12] = 1; indices[13] = 2; indices[14] = 4;

        //face6
        indices[15] = 4; indices[16] = 2; indices[17] = 3;

        rp3d::PolygonVertexArray::PolygonFace* polygonFaces = new rp3d::PolygonVertexArray::PolygonFace[6];
        rp3d::PolygonVertexArray::PolygonFace* face = polygonFaces;

        //each face has 3 indices
        //6 triangles
        for (int f=0; f<6; f++){
                face->indexBase = f*3;
                face->nbVertices = 3;
        }

        std::cout << "created polygon faces" << std::endl;


        //create the polygon vertex array
        rp3d::PolygonVertexArray* pva = new rp3d::PolygonVertexArray(5, vertices, sizeof(float), indices, sizeof(int), 6, polygonFaces, rp3d::PolygonVertexArray::VertexDataType::VERTEX_FLOAT_TYPE, rp3d::PolygonVertexArray::IndexDataType::INDEX_INTEGER_TYPE);

std::cout << "polygon vertex array created" << std::endl;

        //create the polyhedron mesh
        rp3d::PolyhedronMesh* pMesh = new rp3d::PolyhedronMesh(pva);
        std::cout << "polyhedron mesh created" << std::endl;

        //create the convex mesh collision shape
        rp3d::ConvexMeshShape* convexMesh = new rp3d::ConvexMeshShape(pMesh);
        std::cout << "convex mesh shape created" << std::endl;
```

**Comment by DanielChappuis** [comment]
As written in the user manual:

> You need to make sure that the mesh you provide is indeed convex. Secondly, you should provide the simplest possible convex mesh. It means that you need to avoid coplanar faces in your convex mesh shape. Coplanar faces have to be merged together. Remember that convex meshes are not limited to triangular faces, you can create faces with more than three vertices.

**Comment by DanielChappuis** [comment]
Hello,

First, I see an issue when you specify the vertex stride in the constructor of PolygonVertexArray. The vertex stride must be the number of bytes between the beginning of two vertices values in the array. Because the beginning of two vertices in your vertices array is separated by three float values, your stride must be:

`3 * sizeof(float)`

 You can see this in the user manual when I create a cube with this code:

`// Create the polygon vertex array 
polygonVertexArray = new rp3d::PolygonVertexArray(8, vertices, 3 x sizeof(float), 
indices, sizeof(int), 6, polygonFaces, 
rp3d::PolygonVertexArray::VertexDataType::VERTEX_FLOAT_TYPE, 
rp3d::PolygonVertexArray::IndexDataType::INDEX_INTEGER_TYPE); `

Secondly, as written in the user manual:

> You need to make sure that the mesh you provide is indeed convex. Secondly, you should provide the simplest possible convex mesh. It means that you need to avoid coplanar faces in your convex mesh shape. Coplanar faces have to be merged together. Remember that convex meshes are not limited to triangular faces, you can create faces with more than three vertices. 

Therefore, you should really avoid coplanar faces in your mesh. For this reason, when you create your convex mesh for a pyramid with a square base, you should not use two triangles for the base but a square instead. You need to create a polygon face with 4 vertices for the base of your mesh and not two triangle faces.

I hope this helps.

**Comment by auyar1** [comment]
Hi Daniel,

Thank you for the response. That definitely helps a lot.

We have incoming data in the form of 5 vertices, creating a triangle pyramid with a square base.

Is there a way to create a single polyhedron mesh (or another kind of mesh) that incorporates both kinds of faces (triangle side face and square base face)?

Thank you so much for your help.
Aylin

**Comment by DanielChappuis** [comment]
I am not really sure I understand what you want to do. Why do you need a single polyhedron mesh that incorporates both kinds of faces ?

**Comment by auyar1** [comment]
How do I create a mesh of a triangular pyramid with a square base?

**Comment by DanielChappuis** [comment]
If what you want to do is a [pyramid](https://en.wikipedia.org/wiki/Pyramid_(geometry)) (square base), then you need to create a PolyhedronMesh as you did but instead of having 6 PolygonFaces with nbVertices=3, it will have 4 PolygonFaces with nbVertices=3 and another one, the last PolygonFace, for the square base with nbVertices=4.

**Comment by auyar1** [comment]
This is what I have done so far.
Still no resulting polyhedron mesh - I am posting the code below

``` //6 triangle faces
        int indices[16];

        //each face is defined through vertices (ccw)
        //face1
        indices[0] = 0; indices[1] = 3; indices[2] = 2;

        //face2
        indices[3] = 0; indices[4] = 1; indices[5] = 2;

        //face3
        indices[6] = 0; indices[7] = 3; indices[8] = 4;

        //face4
        indices[9] = 0; indices[10] = 1; indices[11] = 4;

        //face5
        indices[12] = 1; indices[13] = 2; indices[14] = 3; indices[15] = 4;

        rp3d::PolygonVertexArray::PolygonFace* polygonFaces = new rp3d::PolygonVertexArray::PolygonFace[5];
        rp3d::PolygonVertexArray::PolygonFace* face = polygonFaces;

        for (int f=0; f<5; f++){
                face->indexBase = f*3;
                face->nbVertices = 3;
                if(f == 4){
                        std::cout << "face is 4" << std::endl;
                        face->indexBase = f*3;
                        face->nbVertices = 4;
                }
                face++;
        }
  //create the polygon vertex array
        rp3d::PolygonVertexArray* pva = new rp3d::PolygonVertexArray(5, vertices, 3*sizeof(float), indices, sizeof(int), 5, polygonFaces, rp3d::PolygonVertexArray::VertexDataType::VERTEX_FLOAT_TYPE, rp3d::PolygonVertexArray::IndexDataType::INDEX_INTEGER_TYPE);
```

**Comment by DanielChappuis** [comment]
Your code seems correct. Now you can create your polyhedron mesh as before with:

```
//create the polyhedron mesh
rp3d::PolyhedronMesh* pMesh = new rp3d::PolyhedronMesh(pva);
```

What do you mean by "Still no resulting polyhedron mesh" ? Something is not working with this code ?

**Comment by auyar1** [comment]
That is what I thought as well - this is the output I am getting from this code - i have a print statement after the polyhedron mesh object is created and it does not output it, or the extra code underneath it.
```
added 4to index0
added 4to index1
added 9to index2
added 0to index3
added 8to index4
added 0to index5
added 0to index6
added 0to index7
added 0to index8
added 8to index9
added 0to index10
added 0to index11
added 8to index12
added 8to index13
added 0to index14
face is 4
created polygon faces
polygon vertex array created
```

**Comment by DanielChappuis** [comment]
You mean that when your application executes the following line:

```
//create the polyhedron mesh
rp3d::PolyhedronMesh* pMesh = new rp3d::PolyhedronMesh(pva);
```

This call does not return ? If you put a breakpoint after this line it is not executed ? or does it crash on this line ?

**Comment by auyar1** [comment]
Yes, that line does not return. The program hangs at that line, and does not execute any commands after it.

```
 //create the polyhedron mesh
        rp3d::PolyhedronMesh* pMesh = new rp3d::PolyhedronMesh(pva);
        std::cout << "polyhedron mesh created" << std::endl;

        //create the convex mesh collision shape
        rp3d::ConvexMeshShape* convexMesh = new rp3d::ConvexMeshShape(pMesh);
        std::cout << "convex mesh shape created" << std::endl;
```

**Comment by auyar1** [comment]
Also, I looked at the code again, and it appears that I get an std::runtime_error

what(): key and value pair already exist in the map

Hope this information helps.
Thanks for all your help

**Comment by DanielChappuis** [comment]
Ok thanks. 

Are you able to execute the code step by step in the debugger to find at which line in the code this error is raised? You will probably need to compile the reactphysics3d library in debug mode to do that.

**Comment by auyar1** [comment]
Hi, I ran the code in Visual Studio debugger.

I came across the issue - runtime error in Map.h line 482 , key value pair already exists in map. That is being called in HalfEdgeStructure::init() line 73, from PolyhedronMesh::createHalfEdgeStructure line 93, from PolyhedronMesh constructor line 48.

My suspicion is that between faces 1 and 2, the edge {2,0} is being used twice. However, I must use this edge to create my faces.

Do you have any suggestions on how to handle this?
Thanks!

**Comment by DanielChappuis** [comment]
You describe the pyramid with the following indices:

>//each face is defined through vertices (ccw)
//face1
indices[0] = 0; indices[1] = 3; indices[2] = 2;
//face2
indices[3] = 0; indices[4] = 1; indices[5] = 2;
//face3
indices[6] = 0; indices[7] = 3; indices[8] = 4;
//face4
indices[9] = 0; indices[10] = 1; indices[11] = 4;
//face5
indices[12] = 1; indices[13] = 2; indices[14] = 3; indices[15] = 4;

I cannot draw the pyramid you describe with your indices with each face being in ccw order. I suspect the issue is coming from the fact that the indices of one or more of your faces are not specified in ccw order. You really need to make sure that the indices of a face are in ccw **as seen from the ouside of the pyramid**.

I have drawn a pyramid on paper and here is how I assign the indices of the faces in ccw order. With this description, I don't have any error.

>indices[0] = 0; indices[1] = 3; indices[2] = 2;
//face2
indices[3] = 0; indices[4] = 2; indices[5] = 1;
//face3
indices[6] = 0; indices[7] = 4; indices[8] = 3;
//face4
indices[9] = 0; indices[10] = 1; indices[11] = 4;
//face5
indices[12] = 1; indices[13] = 2; indices[14] = 3; indices[15] = 4;

**Comment by auyar1** [comment]
yes that was the issue! thank you so much for your help

**Comment by DanielChappuis** [comment]
No problem. You are welcome !
