### ISSUE TITLE
Segmentation fault: 11 on update()

### ISSUE THREAD

**Issue by sanghyunjoo1994** [DanielChappuis/reactphysics3d#95]
Hi, I am currently creating particle simulation using DynamicsWorld().
I keep getting segmentation fault: 11 when I try to run the simulation using update().
Here is the code.
```
void ParticleSimulation::simulate() {
    const float timeStep = 1.0 / 60.0;

    while (simulation_time >= timeStep) {
        simulation_time -= timeStep;
        dynamicsWorld->update(timeStep);
        get_positions_of_bodies();
    }
}
```
I am running the simulation with three sphere rigid bodies
```
body1 : initial position(1.0, 1.0, 1.0), initial velocity(1.1, 1.2, 1.3), radius = 1.0, mass = 10.0
body2 : initial position(10.0, 1.0, 1.0), initial velocity(1.1, 1.2, 1.3), radius = 1.0, mass = 10.0
body3 : initial position(20.0 1.0 1.0), initial velocity(1.1, 1.2, 1.3), radius = 1.0, mass = 10.0
```
I figured out that the update() function gets the error and I am not sure how to investigate the error. Could you give me some advice?

Thank you

**Comment by DanielChappuis** [comment]
Could you please compile and run the library in debug mode and post a stack trace so that I can check where the error occurs ?

**Comment by sanghyunjoo1994** [comment]
Thank you for your quick response.

I am sorry but how do I do that? After compiling with -g option, I got DWARF file. Is this what you need?

Thank you

**Comment by sanghyunjoo1994** [comment]
I found a where the problem comes into
If I comment out the get_positions_of_bodies(), it is OK
```
double x, y, z;
for (size_t i = 0; i < bodies.size(); i++) {
    Vector3 position = Vector3::zero() + bodies[i]->getTransform().getPosition();
    x = position.x;
    y = position.y;
    z = position.z;
    printf("%d: (%f, %f, %f) ", i, x, y, z);
}
printf("\n")
```
Here is the get_positions_of_bodies(). I still don't understand why it causes segmentation fault.

**Comment by DanielChappuis** [comment]
Are you sure your bodies array is correctly initialized ? Can you post the code that you use to create your bodies array ? 

Also, the "Vector3::zero()" in your code doesn't make any sense. Adding zero doesn't do anything.

**Comment by sanghyunjoo1994** [comment]
I am using a vector of pointers of RigidBody.
I assign the bodies with the following code

```
Vector3 position(x, y, z);
Quaternion orientation = Quaternion::identity();
Transform transform(position, orientation);
RigidBody * body = dynamicsWorld->createRigidBody(transform);
bodies.push_back(body);

// set the initial velocity, material, and the shape
set_initial_velocity(body, vx, vy, vz);
set_materials(body, 1.0, 0.0, BodyType::DYNAMIC);
SphereShape sphereShape(r);
body->addCollisionShape(&sphereShape, transform, mass);
```

**Comment by DanielChappuis** [comment]
This is not a stack trace that I can use. I need you to compile the reactphysics3d library in debug mode and post a stack trace where I can see at which line in the code the segmentation fault occurs.

**Comment by sanghyunjoo1994** [comment]
Can you tell me what steps do I have to take?
I used -g option for the compile and I got DWARF file. Is this what you want?
If not, please tell me what steps I should take so I can give that information to you.

**Comment by DanielChappuis** [comment]
I guess that's because at first, you have created a sphere without heap allocation, then your object was released when exiting the function which caused the segmentation fault. Now that you are allocating the sphere object on the heap, your object still exists outside the scope of the function. That's why it's working.

Note that I am closing this issue. Please understand that you have already created 3 issues in a week on this repository but none were issues related to the reactphysics3d library but only questions/issues about basic C++ that all beginners have. This is not a place to learn C++ and I don't have time to teach you C++. I prefer to spend my time improving the library. If you continue to try to learn C++ by posting issues here, you will probably open something like 50 issues in the next month. Note that github issues are for people to report bugs with the software they are using.

If I can give you some advice, please read a book about C++ and do the exercises inside it. That's probably the best way to learn it (that's what I did when I learned C++). There are so many books out there. Once, you have done that if you still have questions, please use developer forums to help you like stackoverflow.com. At this point, you will be able to start using external libraries like reactphysics3d. While doing so, if you think you are almost 90% sure you have found a bug in the library, come back here to post an issue and I will be really happy to help you and try to fix it.
